<?php
/**
 * Dev-only seeder for WordPress Playground. Not shipped in the plugin zip.
 *
 * Reads a Gemini API key from dev/.gemini-key (gitignored), seeds demo
 * products, and writes an application password to dev/.test-app-pass for
 * REST testing.
 *
 * @package DraftPilot
 */

defined( 'ABSPATH' ) || exit;

// 1. Settings (API key from gitignored file, if present).
$draftpilot_key_file = __DIR__ . '/.gemini-key';
$draftpilot_key      = file_exists( $draftpilot_key_file ) ? trim( (string) file_get_contents( $draftpilot_key_file ) ) : '';

update_option(
	'draftpilot_settings',
	array(
		'api_key'      => $draftpilot_key,
		'model'        => 'gemini-3.5-flash',
		'default_tone' => 'professional',
		'brand_voice'  => 'Independent outdoor gear shop. Practical, no hype, durability first.',
		'language'     => 'English',
	),
	false
);

if ( class_exists( 'DraftPilot_Drafts' ) ) {
	DraftPilot_Drafts::maybe_upgrade();
}

// 2. Demo products (only once).
$draftpilot_existing = wc_get_products( array( 'limit' => 1 ) );
if ( empty( $draftpilot_existing ) ) {
	$draftpilot_products = array(
		array( 'Trailblazer 45L Hiking Backpack', 129.99, 'TRB-45', 'Backpacks', array( 'Material' => 'Ripstop nylon', 'Capacity' => '45 L' ) ),
		array( 'Summit Merino Trail Socks (2-Pack)', 24.5, 'SMS-2PK', 'Apparel', array( 'Material' => 'Merino wool blend', 'Sizes' => 'M, L, XL' ) ),
		array( 'Riverstone Insulated Bottle 1L', 34.0, 'RIB-1L', 'Accessories', array( 'Material' => 'Stainless steel', 'Insulation' => '24h cold / 12h hot' ) ),
		array( 'Basecamp Titanium Cook Set', 89.0, 'BTC-SET', 'Cooking', array( 'Material' => 'Titanium', 'Pieces' => 'Pot, pan, lid' ) ),
		array( 'Northwind 3-Season Tent', 249.0, 'NWT-3S', 'Shelter', array( 'Capacity' => '2 person', 'Weight' => '1.9 kg' ) ),
	);

	foreach ( $draftpilot_products as $draftpilot_row ) {
		list( $draftpilot_name, $draftpilot_price, $draftpilot_sku, $draftpilot_cat, $draftpilot_attrs ) = $draftpilot_row;

		$draftpilot_product = new WC_Product_Simple();
		$draftpilot_product->set_name( $draftpilot_name );
		$draftpilot_product->set_regular_price( (string) $draftpilot_price );
		$draftpilot_product->set_sku( $draftpilot_sku );
		$draftpilot_product->set_status( 'publish' );

		$draftpilot_attributes = array();
		foreach ( $draftpilot_attrs as $draftpilot_attr_name => $draftpilot_attr_value ) {
			$draftpilot_attribute = new WC_Product_Attribute();
			$draftpilot_attribute->set_name( $draftpilot_attr_name );
			$draftpilot_attribute->set_options( array_map( 'trim', explode( ',', $draftpilot_attr_value ) ) );
			$draftpilot_attribute->set_visible( true );
			$draftpilot_attributes[] = $draftpilot_attribute;
		}
		$draftpilot_product->set_attributes( $draftpilot_attributes );
		$draftpilot_id = $draftpilot_product->save();

		wp_set_object_terms( $draftpilot_id, $draftpilot_cat, 'product_cat' );
	}
}

// 3. Sample pending drafts so the review queue has content without an API call.
//    (Copy below is real gemini-3.5-flash output generated by this plugin.)
if ( class_exists( 'DraftPilot_Drafts' ) && 0 === DraftPilot_Drafts::count_pending() ) {
	$draftpilot_tent = wc_get_products(
		array(
			'limit' => 1,
			'sku'   => 'NWT-3S',
		)
	);
	if ( ! empty( $draftpilot_tent ) ) {
		$draftpilot_tent_id = $draftpilot_tent[0]->get_id();
		DraftPilot_Drafts::create(
			$draftpilot_tent_id,
			'long_description',
			$draftpilot_tent[0]->get_description(),
			'<p>The <strong>Northwind 3-Season Tent</strong> is a masterfully designed shelter crafted for those who value longevity and refined design in the backcountry. Engineered to perform across three distinct seasons, this premium tent offers a reliable sanctuary without the unnecessary bulk, making it an essential companion for your wilderness expeditions.</p><p>With a focus on practical durability and weight efficiency, this shelter is built to withstand changing outdoor conditions while maintaining a highly manageable pack profile.</p><ul><li><strong>Capacity:</strong> Spacious design comfortably accommodates up to 2 people.</li><li><strong>Weight:</strong> Highly portable trail weight of just 1.9 kg.</li><li><strong>Versatility:</strong> Optimized for reliable 3-season performance.</li></ul>',
			'premium'
		);
		DraftPilot_Drafts::create(
			$draftpilot_tent_id,
			'short_description',
			$draftpilot_tent[0]->get_short_description(),
			'Engineered for dedicated backpackers, the Northwind 3-Season Tent balances refined comfort with reliable durability. Weighing just 1.9 kg, this premium shelter offers a spacious retreat for two adventurers seeking dependable protection in the wild.',
			'premium'
		);
		DraftPilot_Drafts::create(
			$draftpilot_tent_id,
			'meta_description',
			'',
			'Discover the premium Northwind 3-Season Tent. Weighing just 1.9 kg, this durable 2-person shelter is built for refined wilderness comfort. Shop now.',
			'premium'
		);
	}
}

// 4. Dev-only mu-plugin: allow application passwords over plain HTTP.
$draftpilot_mu = WP_CONTENT_DIR . '/mu-plugins';
if ( ! is_dir( $draftpilot_mu ) ) {
	mkdir( $draftpilot_mu ); // phpcs:ignore
}
file_put_contents( // phpcs:ignore
	$draftpilot_mu . '/draftpilot-dev-auth.php',
	"<?php\n" .
	"// Dev-only helpers for the throwaway Playground instance.\n" .
	"add_filter( 'wp_is_application_passwords_available', '__return_true' );\n" .
	"add_action( 'init', function () {\n" .
	"\tif ( isset( \$_GET['draftpilot_dev_login'] ) && ! is_user_logged_in() ) {\n" .
	"\t\t\$u = get_user_by( 'login', 'admin' );\n" .
	"\t\tif ( \$u ) {\n" .
	"\t\t\twp_set_auth_cookie( \$u->ID );\n" .
	"\t\t\twp_safe_redirect( remove_query_arg( 'draftpilot_dev_login' ) );\n" .
	"\t\t\texit;\n" .
	"\t\t}\n" .
	"\t}\n" .
	"} );\n"
);

// 5. Application password for REST testing.
$draftpilot_admin = get_user_by( 'login', 'admin' );
if ( $draftpilot_admin && class_exists( 'WP_Application_Passwords' ) ) {
	$draftpilot_created = WP_Application_Passwords::create_new_application_password(
		$draftpilot_admin->ID,
		array( 'name' => 'draftpilot-dev-' . time() )
	);
	if ( ! is_wp_error( $draftpilot_created ) ) {
		file_put_contents( __DIR__ . '/.test-app-pass', $draftpilot_created[0] ); // phpcs:ignore
	}
}
